bw-green/ChessGame

src/board/Board.java, src/piece/King.java, src/piece/Pawn.java, src/piece/Rook.java, src/specialRule/SpecialRule.java
=> feature) SpecialRule 추가와 그에 맞는 Board와  Piece들에 대한 여러 수정

src/fileManager/FileManager.java, src/test/java/filemanager/FileManagerTest.java
Deque에 Input 추가하는건 Input쪽 완성되면 복구시키겠습니다. 지금은 주석처리 되있습니다.
Deque쪽 포함해서 모든 기능 테스트 완료했습니다.
=> FileManger first upload.

chessGame.iml, src/board/Board.java, src/data/CommandError.java, src/data/Error.java, src/data/FileError.java, src/data/InvalidCoordinate.java, src/data/Unspecified.java, src/fileManager/FileManager.java, src/mainChess.java, src/piece/King.java, src/piece/Pawn.java, src/piece/Rook.java, src/specialRule/SpecialRule.java, src/test/java/ErrorTest.java, src/test/java/board/BoardTest.java, src/test/java/filemanager/FileManagerTest.java, src/test/java/piece/PawnEnPassantTest.java, src/test/java/piece/PawnPromotionTest.java
에러메세지, 체크 하는기능 앙파상, 프로모션확인
캐슬링기능 확인안함
=> develop 최신화 4/13 오후 9시 15분

src/data/Command.java, src/data/PrintTemplate.java, src/test/CommandTest.java
Command 및 PrintTemplate enum class, Command Test 까지 완료했습니다.
=> command messages and test

src/Input/GameInput.java, src/data/GameInputReturn.java, src/test/java/Input/GameInputTest.java
오류 뜨는 곳만 sout 해주었고
모든 값은 return으로 처리해주었고
인자들은 number로 사용하면되고
GameInput.gameInput()-> 입력받고 return int나옴 뭔지는 Enum에 정의
GameInput.number-> 입력인자 있으면 여기서 빼오면 된다
=> In game input

src/Input/GameInput.java, src/test/java/Input/GameInputTest.java
=> [!HOTFIX] gameInput 오류 해결

src/data/GameInputReturn.java, src/test/java/Input/UserInputTest.java, src/userinput/UserInput.java
UserInput Test 케이스 추가 UserInput return 값 변경
=> UserInput Test 케이스 추가 UserInput return 값 변경

src/Menu/MenuInput.java, src/TestMain.java, src/gameManager/GameManager.java, src/mainChess.java
=> mainChess로 돌리기

src/board/Board.java, src/data/MoveErrorType.java
=> king 체크 문구 추가

src/Input/GameInput.java, src/Menu/MenuInput.java, src/data/Command.java, src/gameManager/GameManager.java
Command 관련 문구 출력 기획서 Mockup과 맞춤 <- 기획서에도 Mockup 수정 사항 있을 예정
Command 관련 Error 출력 <- Load는 아직 미완료
=> Gamemanager

src/TestMain.java, src/board/Board.java
TestMain.java에 TC 코드 추가.
*Confilct?* ->> Board.java에 iscellUnderAttack() 함수 주석처리 한 것 삭제해도 무방
(이제 안 쓰는 함수라 주석처리 혹은 삭제하는게 나을듯 싶네요)
=> Test Case 추가(보드/셀/피스)

src/Menu/Menu.java, src/data/PrintTemplate.java, src/gameManager/GameManager.java
menu 출력, PrintTemplate 관련 수정사항
=> gamemagner

.idea/misc.xml, src/TestMain.java, src/board/Board.java
보드 내에서 PrintTemplate.BORDLINE 추가
=> 의미 규칙 메시지 출력 수정

src/data/FileMessage.java
FileManager Patch 9.1.1 1. FileMessage.LSF_LINE 안에 알파벳 소문자로 통일
=> FileManager Patch 9.1.1 1. FileMessage.LSF_LINE 안에 알파벳 소문자로 통일

src/board/Board.java
=> 오류나서 생성자추가

src/board/ThreeCheckBoard.java
=> ThreeCheckBoard

src/Menu/Menu.java, src/Menu/MenuInput.java, src/data/Command.java, src/data/PrintTemplate.java, src/gameManager/GameManager.java
=> gamemanager 

src/Menu/MenuInput.java, src/data/Command.java, src/data/PrintTemplate.java, src/gameManager/GameManager.java
isGameEnd() 수정, Command 출력 문구 수정
=> Game manager

src/fileManager/FileManager.java, src/fileManager/SaveIntegrityChecker.java
FileManager 저장 부분 오류 수정
무결성 검사
-보드 생성 후 필요값 대입 부분 구현
- 메서드 내부 값들 오류 수정
=> patch 12.0.5(FileManager,SaveIntegrityChekcer 수정)

src/fileManager/FileManager.java, src/fileManager/SaveIntegrityChecker.java, src/test/java/SaveIntegrityChecker/SICTest.java, src/test/java/file/SaveFileTest.java, src/test/java/file/UserManagerTest.java
- checkPieceSymbols(): value값에 공백 허용에 따른 trim() 추가, gameType에 따른 허용 기물 수정
- checkPieceCoordinates(): row, col 서로 바뀌어 저장되는 부분 수정, 빈 칸 처리할 때 symbol -> expectedSymbol 수정
- validateFile(): row, col 서로 바뀌어 저장되는 부분 수정
- validateValueByKey(): ID 9글자 -> 10글자 수정
- checkPieceSymbols(): 폰게임 허용 기물 Set 따로 추가
SICTest.java
- 아래 함수들 테스트 케이스 검사 완료
validateFile()
checkPieceSymbols()
checkKingCount()
checkRuleFlags()
checkThreeCheckSettings()
checkPieceCoordinates()
checkGameEnd()
- 폰게임의 폰을 P,p -> Z,z로 변경
=> SaveIntegrityChecker 클래스 수정, 테스트 케이스 추가
